server.port=8080

caiyun.auth.enable=true
caiyun.auth.user-name=admin
caiyun.auth.password=admin
# The in-memory threshold for temporary files during upload (e.g., 100MB).
# If the file size exceeds this value, temporary files will be stored on the disk instead.
caiyun.cacheMemoryLimit=104857600
